# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OsSbQLd-_Y6-nK1FCw40zU67R1d9j0_k
"""

def tashxis(belgi):
  if belgi=="istima":
    return "parastamol ich"
  elif belgi =="kataraka":
    return " Deksamitazon"
  elif belgi== "bosh ogrigi":
    return "trimol"
  elif belgi == "gripp":
    return "Taylalhot"
  else:
    return " Shifokorga murojat qiling"
belgi= input ("kasallik belgisini kiriting ")
natija=tashxis  (belgi)
print (natija)

from google.colab.patches import cv2_imshow
import cv2
def telefon(modeli):
  if   modeli=="iphone x":
    rasm1=cv2.imread("/65414af8fd4858736a695a7e-pre-owned-apple-iphone-x-256gb-factory.jpg")
    cv2_imshow(rasm1)
    return "230$"
  elif modeli =="iphone 11 pro":
    rasm1=cv2.imread("/photo_2024-11-21_16-01-35.jpg")
    cv2_imshow(rasm1)
    return "300$"
  elif modeli== "iphone 12 pro":
    rasm1=cv2.imread("/photo_2024-11-21_17-35-17.jpg")
    cv2_imshow(rasm1)
    return "420$"
  elif modeli == "iphone 13 pro":
    rasm1=cv2.imread("/photo_2024-11-21_17-40-39.jpg")
    cv2_imshow(rasm1)
    return "550$"
  elif modeli== "iphone 14 pro":
    rasm1=cv2.imread("/photo_2024-11-21_17-42-29.jpg")
    cv2_imshow(rasm1)
    return "680$"
  elif modeli =="iphone 15 pro":
    rasm1=cv2.imread("/photo_2024-11-21_17-43-59.jpg")
    cv2_imshow(rasm1)
    return "800$"
  elif modeli =="iphone 16 pro":
    rasm1=cv2.imread("/photo_2024-11-21_17-44-24.jpg")
    cv2_imshow(rasm1)
    return "1280$"
  else:
    return " telefon dokoniga murojat qiling"
modeli= input ("telfon rusimini kiriting ")
natija=telefon (modeli)
print (natija)